import Head from 'next/head'
// import styled from 'styled-components'
import { WeightEntity } from '@/entities'

// const Wrapper = styled.div`
//   margin: 24px 0;
// `

// const OutSideWrapper = styled.div`
//   margin: 0 -16px 16px;
// `

type Props = {
  weights: Array<WeightEntity>
}

export const SpScreen = ({ weights }: Props): JSX.Element => {
  return (
    <div className="">
      <Head>
        <title>My Wight Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">How is your goal??</h1>
      </main>

      {weights.map((weight, index) => (
        <div key={index}>
          <p>{weight.weight}</p>
          <p>{weight.workOutDate}</p>
        </div>
      ))}

      <footer className="">
        <p>Powered by Takaki Miyajima</p>
      </footer>
    </div>
  )
}
