import React from 'react'
import Head from 'next/head'
import { SpScreen } from "@/components/sp/screens"
import { useUserAgent } from "@/contexts/userAgent/useUserAgent"
import { WeightEntity } from '@/entities'
import { WeightRepository } from '@/repositories'

type Props = {
  weights: Array<WeightEntity>
}

export async function getServerSideProps() {
  try {
    const weights = await WeightRepository.fetchWeights()

    return {
      props: {
        weights
      }
    }
  } catch (error) {
    console.log(error)
  } 
}

export default function Home(props: Props) {
  // TODO: when data missing, show error page

  const userDevice = useUserAgent()
  // TODO: prepare some components
  return (
    <>
      <Head>
        <title>My Weight Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {userDevice.isMobile ? (
        <SpScreen weights={props.weights} />
      ) : (
        <p>Under Construction for PC</p>
        // <PcContent data={props} />
      )}
    </>
  )
}
